---
# Usage: http://ruhoh.com/usage/configure/

RuhohSpec: '1.0'
theme : twitter
production_url : http://osteele.com/posts/

posts:
  permalink: /posts/:year/:month/:title
  summary_lines: 10
  latest: 10

pages:
  permalink: 'pretty'
