title : Oliver Steele
tagline: Languages of the real and artifical
author :
  name : Oliver Steele
  email : steele@osteele.com
  github : osteele
  twitter : osteele
  feedburner : osteele

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

